@startuml
package utils/cs {
    class Main << (S,#FF7700) struct >> {
        + main()
    }

    class MenuController << (S,#FF7700) struct >> {
        - List num_history
        + select(num, args[])
    }

    class MenuArgument << (T,#777700) type >> {
        + execute (num, args[])
    }

    interface MenuItem << interface >> {
        + execute (MenuArgument args)
    }

    class DeploymentApp << (S,#FF7700) struct >> {
        + execute (MenuArgument args)
    }

    class CreateContainerPack << (S,#FF7700) struct >> {
        + execute (MenuArgument args)
    }

    class Quit << (S,#FF7700) struct >> {
        + execute (MenuArgument args)
    }

    Main .> MenuController : create
    MenuController ..> MenuItem : execute
    MenuItem *. MenuArgument
    MenuItem <|.. DeploymentApp
    MenuItem <|.. CreateContainerPack
    MenuItem <|.. Quit

}
@enduml
