@startuml
package github.com/keita69/cs/main {
    class cs << (S,#FF7700) struct >> {
        + main()
    }
}
package github.com/keita69/cs/menu {
    class MenuController << (S,#FF7700) struct >> {
        - List num_history
        + select(num, args[])
    }

    class MenuArgument << (T,#777700) type >> {
        + execute (MenuArgument args)
    }

    interface MenuItem << interface >> {
        + execute (MenuArgument args)
    }

    class DeploymentApp << (S,#FF7700) struct >> {
        + execute (MenuArgument args)
    }

    class CreateContainerPack << (S,#FF7700) struct >> {
        + execute (MenuArgument args)
    }

    class Quit << (S,#FF7700) struct >> {
        + execute (MenuArgument args)
    }
}

    cs .> MenuController : create
    MenuController ..> MenuItem : execute
    MenuItem *. MenuArgument
    MenuItem <|.. DeploymentApp
    MenuItem <|.. CreateContainerPack
    MenuItem <|.. Quit

@enduml
